### ISSUE TITLE
Extension failed to compile during installation of rails

### ISSUE THREAD

**Issue by Justinhoejj** [CVWO/setup-guide#2]
Attempted to install rails using the following website up to step 3.1.4 where I encountered a compilation error.
https://guides.rubyonrails.org/getting_started.html
Following screen shot shows the error report. Please advice on how I should go about resolving this.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/68779715/101274036-b63dd780-37d5-11eb-8743-a5e3a17098ac.png">

**Comment by Justinhoejj** [comment]
Cannot use default Ruby on Mac OS to install rails. Used ruby version manager to install ruby and subsequently rails.
https://www.youtube.com/watch?v=Qn-1egqgsnM

**Comment by zhuhanming** [comment]
Hi Justin, glad to see that you've managed to resolve the issue! I'll be reopening this issue so that anyone who has the same problem can refer to this.

Do also label the issue accordingly in the future!
