### ISSUE TITLE
Cannot enter localhost:3000 

### ISSUE THREAD

**Issue by wengYing227** [CVWO/setup-guide#3]
Hi, I have gone through the instructions on https://gorails.com/setup/windows/10

But for the last step, I cannot open locahost:3000 
The page displays : localhost refused to connect.   [ERR_CONNECTION_REFUSED]

BTW, I can enter http://localhost/
and I installed Ruby and MySQL.

I will appreciate it if you could help me!! =)

**Comment by Asthenosphere** [comment]
Not sure if this helps as I'm not on Windows, but can you try a different port using `rails s -p 3001` for example? Or try to run the server using `rails s -b 0.0.0.0`.

**Comment by wengYing227** [comment]
> Not sure if this helps as I'm not on Windows, but can you try a different port using `rails s -p 3001` for example? Or try to run the server using `rails s -b 0.0.0.0`.

It still doesn't work. It seems that the windows system usually occurs some problems when installing or running ROR. nvm I am trying to solve it by installing the Linux virsual machine. 
Thanks anyway =)
