### ISSUE TITLE
`rake db:create` could not connect to server: Connection refused

### ISSUE THREAD

**Issue by SkyBlaise99** [CVWO/setup-guide#5]
I'm at the final step ([here](https://gorails.com/setup/windows/10#final-steps)) where I need to create DB. The following error shows up when I run `rake db:create`.

![image](https://user-images.githubusercontent.com/69448615/145713224-6d9ee44a-b93d-4420-a5aa-da3761ec61af.png)

Using `Win 11` with `WSL Ubuntu 20.04 LTS`. I followed all steps above with no error along the way. Installed `rbenv` & `PostgreSQL on Windows`. Kept the username and password and I'm able to log in as shown here.

![image](https://user-images.githubusercontent.com/69448615/145713412-0ac04040-62e1-4f45-b2bb-da3367ce79bb.png)

Searched through the `Comments` section in the same link above and found some suggestions but none of them works, most of the answers are regarding the Linux version and not the windows version. Some suggest that the server is not started which isn't the case for me as I have another program that uses `PostgreSQL` as well and that one can run normally.

Tried adding the following into `config/database.yml` but still the same error.

![image](https://user-images.githubusercontent.com/69448615/145713647-b555e2b3-8a6a-439c-bbad-0bfb0a39ae25.png)
![image](https://user-images.githubusercontent.com/69448615/145713654-b06c3fda-1f6b-4670-a7c5-01a4d23b3f38.png)

Has anyone encountered this or has any suggestions? Thanks in advance for helping.

**Comment by zognin** [comment]
@SkyBlaise99 Hello your config seems correct. You mentioned installing PostgresSQL on Windows. However you are running Ruby on Rails on WSL. Hence, you could install and use PostgresSQL on WSL too.

Afterwards, if you are running postgres on both Windows and WSL, there may be a conflict. [This may be helpful](https://jaykilleen.com/posts/debugging-postgresl-and-rails-pg-connectionbad-could-not-connect-to-server-connection-refused).

Hope this helps, I haven't used WSL or Windows before so I'm not sure about the exact problem too.

**Comment by SkyBlaise99** [comment]
@zognin thx for the reply.

The strange thing is that I have another project that uses the installed PostgresSQL DB and that one is running perfectly fine. I double checked using pgAdmin4 which shows that the server is running and my other project can also connect to the DB successfully.

One thing which might be the cause is that my rails is on WSL while PostgresSQL is on windows, but the tutorial does not show any information on this and I also find some online YouTube guide which shows that it is possible to have rails on WSL and PostgresSQL on Windows.

Yeah last resort will be to have PostgresSQL on WSL like you mentioned.

**Comment by zognin** [comment]
@SkyBlaise99 yup do try using PostgresSQL on WSL and let us know if it works! Parts of a tutorial on the internet may not always be the best way forward

**Comment by SkyBlaise99** [comment]
@zognin PostgreSQL on WSL works. I'm able to create DB and start on the assignment! Thx for the info although I didn't need to use them.

**Comment by InfiBeyond** [comment]
> @zognin thx for the reply.
> 
> The strange thing is that I have another project that uses the installed PostgresSQL DB and that one is running perfectly fine. I double checked using pgAdmin4 which shows that the server is running and my other project can also connect to the DB successfully.
> 
> One thing which might be the cause is that my rails is on WSL while PostgresSQL is on windows, but the tutorial does not show any information on this and I also find some online YouTube guide which shows that it is possible to have rails on WSL and PostgresSQL on Windows.
> 
> Yeah last resort will be to have PostgresSQL on WSL like you mentioned.

I'm facing the same issue. Would you mind sharing the youtube video that you used? Thank you very much.

**Comment by SkyBlaise99** [comment]
@InfiBeyond Altho in the Youtube video it works, it didn't work for me on my laptop following the exact way. Here's the [link](https://www.youtube.com/watch?v=u_JFDqax0l0) anyways, it's a pretty old one so I guess there might have been updates that made it not working anymore.

I end up installing on WSL, the command should be just `sudo apt-get install postgresql`. I dug my history and this [link](https://harshityadav95.medium.com/postgresql-in-windows-subsystem-for-linux-wsl-6dc751ac1ff3) should be the one I used.

The thing about running it on WSL is that you have to start the server every time your comp shuts down, either manually or with a script.

**Comment by WuHaohui1231** [comment]
@SkyBlaise99 Hi. I'm facing the same issue. I tried installing PostgreSQL on WSL like you mentioned. My I still cannot get it working. It seems like I'm not using it as the user "postgres". But when I log in to postgres the other commands doesn't work. How did you get it into working? Could you please provide some details? Thanks.
![image](https://user-images.githubusercontent.com/95847459/147942412-1f5f7eb8-58da-40ac-a323-dcd9d645f134.png)

**Comment by SkyBlaise99** [comment]
@WuHaohui1231 try the following steps

1. Enter psql as user postgres
2. Create a new user with the same username as ur WSL, in ur case `haohui`
3. Add permissions to the new user (create, edit db stuffs)
4. Try the DB create command again

P.S. Sry I'm typing on phone so have to omit some details, but they should all be easily found with Google.
