### ISSUE TITLE
"Could not find database: postgres"

### ISSUE THREAD

**Issue by WuHaohui1231** [CVWO/setup-guide#6]
I followed this guide https://gorails.com/setup/windows/10. But on the final step when I run rake db:create, it gives me an error like this.
Is this because I didn't "edit config/database.yml to match the user you created earlier". But how can I access config/database.yml and edit it?
<img width="908" alt="issue" src="https://user-images.githubusercontent.com/95847459/147664882-cddb3dcc-86a0-4605-a2fe-43807a64d46e.png">

**Comment by kaixin-hc** [comment]
To find config/database.yml, go inside the config folder and open the database.yml file. I think most IDEs should let you edit `.yml` files.

For your issue in particular, it doesn't look like a user authentication issue. Perhaps you could try the solution suggested in the first answer here? https://stackoverflow.com/questions/25611004/rake-dbcreate-throws-database-does-not-exist-error-with-postgresql

All the best.

**Comment by WuHaohui1231** [comment]
I tried all the suggestions but they didn't work :( .
